// Register user

export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

// lOGIN ACTION

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// MENU ITEMS FETCH

export const FETCH_ITEMS_START = "FETCH_ITEM_START"
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEM_SUCCESS"
export const FETCH_ITEMS_FAILURE = "FETCH_ITEM_FAILURE"

//ADD MENU ITEM

export const ADD_ITEM_START = "ADD_ITEM_START"
export const ADD_ITEM_SUCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"

//GET RECIPE BY USER

// export const FETCH_RECIPESBYUSER_START = "FETCH_RECIPESBYUSER_START"
// export const FETCH_RECIPESBYUSER_SUCCESS = "FETCH_RECIPESBYUSER_SUCCESS"
// export const FETCH_RECIPESBYUSER_FAILURE = "FETCH_RECIPESBYUSER_FAILURE"

//DELETE ACTION

export const DELETE_ITEM_START = "DELETE_ITEM_START"
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE"

//UPDATE ACTIONS

export const UPDATE_ITEM_START = "UPDATE_ITEM_START"
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE"

//export const ADD_RECIPE_EDIT = "ADD_RECIPE_EDIT"